# Generated by Django 4.0.5 on 2022-09-16 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_alter_contact_body_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 15, 5, 18, 552239), verbose_name='تاریخ دریافت'),
        ),
    ]
