# Generated by Django 4.0.5 on 2022-09-16 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0023_alter_contact_recived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 15, 11, 40, 711342), verbose_name='تاریخ دریافت'),
        ),
    ]
