# Generated by Django 4.0.5 on 2022-09-18 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_alter_contact_recived_at_ticketchild_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 15, 7, 56, 821746), verbose_name='تاریخ دریافت'),
        ),
    ]
