# Generated by Django 4.0.5 on 2022-09-18 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_alter_contact_body_alter_contact_recived_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AddField(
            model_name='ticketchild',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_ticket', to='contact.ticket', verbose_name='جواب به'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 15, 31, 32, 407512), verbose_name='تاریخ دریافت'),
        ),
    ]
