# Generated by Django 4.0.5 on 2022-09-20 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0027_alter_ticket_options_ticketchild_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 16, 48, 2, 376570), verbose_name='تاریخ دریافت'),
        ),
    ]
