# Generated by Django 4.0.5 on 2022-09-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_alter_contact_recived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 17, 40, 10, 604743), verbose_name='تاریخ دریافت'),
        ),
    ]
