# Generated by Django 4.0.5 on 2022-09-23 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0030_alter_contact_recived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 16, 5, 27, 296971), verbose_name='تاریخ دریافت'),
        ),
    ]
