# Generated by Django 4.2.1 on 2023-09-16 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0032_alter_contact_recived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 15, 51, 0, 2863), verbose_name='تاریخ دریافت'),
        ),
    ]
