# Generated by Django 4.2.5 on 2023-09-16 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_alter_contact_recived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recived_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 18, 39, 17, 689899), verbose_name='تاریخ دریافت'),
        ),
    ]
