# Generated by Django 4.0.5 on 2022-07-20 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_rename_profile_karbar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Karbar',
            new_name='Profile',
        ),
    ]
