# Generated by Django 4.0.5 on 2022-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_karbar_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='melicode',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
