# Generated by Django 4.0.5 on 2022-09-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub',
        ),
    ]
