# Generated by Django 4.0.5 on 2022-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_author_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='یک عنوان مناسب برای مقاله انتخاب شود.', max_length=100, verbose_name='عنوان'),
        ),
    ]
