# Generated by Django 4.0.5 on 2022-09-20 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislike',
            field=models.ManyToManyField(related_name='article_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='دیس لایک'),
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='article_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
