# Generated by Django 4.0.5 on 2022-09-21 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_article_dislike_article_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='viewers',
        ),
        migrations.AddField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(related_name='article_viewers', to=settings.AUTH_USER_MODEL, verbose_name='تعداد بازدید'),
        ),
    ]
