# Generated by Django 4.0.5 on 2022-09-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_article_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislike',
        ),
    ]
