# Generated by Django 4.0.5 on 2022-09-23 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_remove_article_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislike',
            field=models.ManyToManyField(related_name='article_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='دیس لایک'),
        ),
    ]
